CREATE TABLE IF NOT EXISTS ladder_steps (
  id SERIAL PRIMARY KEY,
  boss_question_id INTEGER REFERENCES boss_questions(id),
  step_number INTEGER NOT NULL,
  concept_tag TEXT,
  question_type TEXT DEFAULT 'mcq',
  question_text TEXT NOT NULL,
  question_image_url TEXT,
  option_a TEXT,
  option_a_image_url TEXT,
  option_b TEXT,
  option_b_image_url TEXT,
  option_c TEXT,
  option_c_image_url TEXT,
  option_d TEXT,
  option_d_image_url TEXT,
  correct_options TEXT NOT NULL,
  marks INTEGER DEFAULT 4,
  hint_text TEXT,
  explanation TEXT,
  theory_card TEXT,
  video_url TEXT,
  difficulty TEXT DEFAULT 'medium',
  target_exam TEXT DEFAULT 'all',
  source TEXT,
  language TEXT DEFAULT 'english',
  is_boss_step BOOLEAN DEFAULT false,
  is_prefetch_ready BOOLEAN DEFAULT false,
  version INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);