CREATE TABLE IF NOT EXISTS clone_questions (
  id SERIAL PRIMARY KEY,
  original_step_id INTEGER REFERENCES ladder_steps(id),
  question_text TEXT NOT NULL,
  question_image_url TEXT,
  option_a TEXT,
  option_a_image_url TEXT,
  option_b TEXT,
  option_b_image_url TEXT,
  option_c TEXT,
  option_c_image_url TEXT,
  option_d TEXT,
  option_d_image_url TEXT,
  correct_options TEXT NOT NULL,
  explanation TEXT,
  theory_card TEXT,
  hint_text TEXT,
  difficulty TEXT DEFAULT 'medium',
  language TEXT DEFAULT 'english',
  is_approved BOOLEAN DEFAULT false,
  is_prefetch_ready BOOLEAN DEFAULT false,
  prefetch_generated_at TIMESTAMP,
  times_used INTEGER DEFAULT 0,
  version INTEGER DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW()
);