CREATE TABLE IF NOT EXISTS landing_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT '',
  label TEXT NOT NULL DEFAULT '',
  section TEXT NOT NULL DEFAULT 'general',
  updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO landing_content (key, value, label, section) VALUES
  ('hero_badge',           'For JEE (Main + Advanced) & NEET Aspirants',                        'Hero Badge Text',            'hero'),
  ('hero_h1_line1',        'Learn Smarter.',                                                     'Hero Heading Line 1',        'hero'),
  ('hero_h1_line2',        'Master Every Concept.',                                              'Hero Heading Line 2',        'hero'),
  ('hero_sub',             'At Gokoo, every wrong answer is a step towards success. Our adaptive ladder system ensures you truly understand every concept — not just memorise it.',  'Hero Subtitle',  'hero'),
  ('hero_cta_primary',     'Start Your Journey →',                                               'CTA Primary Button',         'hero'),
  ('hero_cta_secondary',   'Watch System',                                                       'CTA Secondary Button',       'hero'),
  ('features_title1',      'Concept-First Learning',                                             'Feature 1 Title',            'features'),
  ('features_desc1',       'We don''t teach shortcuts. Every concept is broken down to its roots so you actually understand — and never forget.',  'Feature 1 Description',  'features'),
  ('features_title2',      'Adaptive Ladder System',                                             'Feature 2 Title',            'features'),
  ('features_desc2',       'Wrong answers aren''t failures — they''re signals. Our system adapts to your gaps and rebuilds from the foundation up.',  'Feature 2 Description',  'features'),
  ('features_title3',      'JEE & NEET Focused',                                                 'Feature 3 Title',            'features'),
  ('features_desc3',       'Every question, every concept, every ladder is built specifically for JEE Main, JEE Advanced, and NEET — nothing irrelevant, nothing missing.',  'Feature 3 Description',  'features'),
  ('features_title4',      'Track Every Step',                                                   'Feature 4 Title',            'features'),
  ('features_desc4',       'See exactly where you stand. Track your ladder completions, accuracy rates, and point streaks — all in real time.',  'Feature 4 Description',  'features'),
  ('trusted_tagline',      'Trusted by thousands of JEE & NEET aspirants across India',         'Trusted Section Tagline',    'trusted'),
  ('hiw_tag',              'The System',                                                         'How It Works Tag',           'how_it_works'),
  ('hiw_h2',               'From Zero to Mastery in 4 Steps',                                   'How It Works Heading',       'how_it_works'),
  ('hiw_desc',             'A structured path that builds real understanding, not just marks.',  'How It Works Description',   'how_it_works'),
  ('hiw_step1_title',      'Choose Your Concept',                                                'Step 1 Title',               'how_it_works'),
  ('hiw_step1_desc',       'Pick any subtopic from Physics, Chemistry, Maths, or Biology. Start wherever you need.',  'Step 1 Description',  'how_it_works'),
  ('hiw_step2_title',      'Attempt the Boss Question',                                          'Step 2 Title',               'how_it_works'),
  ('hiw_step2_desc',       'Each concept has a challenging Boss Question. Try it first — it reveals exactly what you don''t know.',  'Step 2 Description',  'how_it_works'),
  ('hiw_step3_title',      'Climb the Ladder',                                                   'Step 3 Title',               'how_it_works'),
  ('hiw_step3_desc',       'A sequence of 6–8 guided steps rebuilds your understanding from the ground up. Each step is perfectly sized — not too easy, not too hard.',  'Step 3 Description',  'how_it_works'),
  ('hiw_step4_title',      'Earn Points & Level Up',                                             'Step 4 Title',               'how_it_works'),
  ('hiw_step4_desc',       'Complete ladders to earn points, climb the leaderboard, and unlock new concepts. Progress you can see and feel.',  'Step 4 Description',  'how_it_works'),
  ('courses_tag',          'Our Courses',                                                        'Courses Section Tag',        'courses'),
  ('courses_h2',           'Choose Your Course',                                                 'Courses Section Heading',    'courses'),
  ('courses_desc',         'Structured programs designed specifically for JEE Main, JEE Advanced, and NEET aspirants — from Class 11 to Dropper batches.',  'Courses Description',  'courses'),
  ('about_tag',            'About Us',                                                           'About Section Tag',          'about'),
  ('about_h2',             'Built by Educators, Driven by Students',                             'About Section Heading',      'about'),
  ('about_para1',          'Gokoo was built after watching thousands of students struggle with the same problem: they could solve examples but fell apart in exams. The reason? Shallow understanding.',  'About Paragraph 1',  'about'),
  ('about_para2',          'We built Gokoo to fix that. Our ladder system forces deep understanding at every level. Every concept is connected, every gap is identified, and every student gets the exact practice they need.',  'About Paragraph 2',  'about'),
  ('cta_h2',               'Stop Watching. Start Doing.',                                        'CTA Section Heading',        'cta'),
  ('cta_p',                'Start mastering concepts today — one ladder at a time.',             'CTA Section Description',    'cta'),
  ('cta_note',             '✓ JEE & NEET focused · ✓ Expert faculty · ✓ Concept based learning',  'CTA Note Text',  'cta'),
  ('footer_tagline',       'Concept-first learning for JEE & NEET aspirants.',                  'Footer Tagline',             'footer')
ON CONFLICT (key) DO NOTHING;
