ALTER TABLE ladder_steps
  ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'T1',
  ADD COLUMN IF NOT EXISTS rung INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_mastery_gate BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS insight_correct TEXT,
  ADD COLUMN IF NOT EXISTS insight_wrong TEXT;
